export const SEND_WEATHER_REQUEST = "SEND_WEATHER_REQUEST"
export const RECEIVE_WEATHER_RESPONSE = "RECEIVE_WEATHER_RESPONSE"
export const RECEIVE_WEATHER_ERROR = "RECEIVE_WEATHER_ERROR"



export const SEND_FORECAST_REQUEST = "SEND_FORECAST_REQUEST";
export const RECEIVE_FORECAST_RESPONSE = "RECEIVE_FORECAST_RESPONSE";
export const RECEIVE_FORECAST_ERROR = "RECEIVE_FORECAST_ERROR";
